server:
  port: 9060
spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: 192.168.33.22
    port: 5672
    username: root
    password: root
    virtual-host: /
    publisher-confirms: true #开启消息发送确认，默认为false,消息到达exchange确认
    publisher-returns: true #开启消息失败回调，默认false，exchange到达queue确认
    listener:
      simple:
        acknowledge-mode: MANUAL #NONE：自动确认,AUTO：根据情况确认,手动确认

#消息队列配置
mq:
  ipAddress: 172.168.33.22 #本机ip地址
  paymentTopic: PaymentMessage

logging:
  path: /mnt/logs #日志输出位置
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n" #控制台日志数据格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n" #输出格式
    dateformat: yyyy-MM-dd HH:mm:ss #日志时间格式
    level: INFO  #日志输出级别
  file:
    max-size: 500MB
    max-history: 1
    
    



