#druid数据库连接池
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    url: jdbc:mysql://localhost:3306/finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root #测试
    password: zhao4443 #测试
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      #连接池配置
      initial-size: 10 #初始化时建立物理连接的个数
      min-idle: 2 #最小连接池数量
      max-active: 50 #最大连接池数量
      max-wait: 60000 #连接等待超时的时间
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效
      test-on-return: false #归还连接时执行validationQuery检测连接是否有效
      time-between-log-stats-millis: 300000 #输出监控日志
      filters: stat,wall,slf4j #监控统计用的filter:stat 日志用的filter:slf4j防御sql注入的filter:wall
      filter:
        stat: #配置StatFilter
          slow-sql-millis: 2000 #执行时间超过3秒为慢sql
          log-slow-sql: true  #打印慢sql
          merge-sql: true #sql合并
          db-type: mysql
          enabled: true
        slf4j: #配置slf4j
          enabled: true
          connection-log-enabled: true
          connection-close-after-log-enabled: true
          connection-commit-after-log-enabled: true
          connection-connect-after-log-enabled: true
          connection-connect-before-log-enabled: true
          connection-log-error-enabled: true
          data-source-log-enabled: true
          result-set-log-enabled: true
          statement-log-enabled: true
        wall:
          enabled: true
          db-type: mysql
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
            none-base-statement-allow: false #是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL。
            update-where-alay-true-check: true #检查UPDATE语句是否无where条件，这是有风险的，但不是SQL注入类型的风险
            select-into-outfile-allow: false #SELECT ... INTO OUTFILE 是否允许，这个是mysql注入攻击的常见手段，缺省是禁止的
            metadata-allow: true #是否允许调用Connection.getMetadata方法，这个方法调用会暴露数据库的表信息
          log-violation: true #对被认为是攻击的SQL进行LOG.error输出
          throw-exception: true #对被认为是攻击的SQL抛出SQLExcepton
      #use-global-data-source-stat: true #合并监控数据
      web-stat-filter: #配置web-stat-filter
        enabled: true 
        url-pattern: /*
        exclusions: /druid/*,*.ico,*.js,*.gif,*.jpg,*.png,*.css
      stat-view-servlet: #配置web-view-servlet
        enabled: true
        #deny: 172.16.0.21,172.16.0.22,172.16.0.23,172.16.0.24 #允许登录ip,deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。
        #allow: 172.16.0.21,172.16.0.22,172.16.0.23,172.16.0.24 #允许登录ip,deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。
        reset-enable: true #清空统计数据
        login-username: staff #登录用户
        login-password: staff #登录密码
        url-pattern: /druid/*