spring:
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 600000 #cacheble时间10分钟，单位毫秒
  redis:
    host: localhost
    port: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 5 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait:  10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle:  8 # 连接池中的最大空闲连接默认 8
        min-idle:  0 # 连接池中的最小空闲连接默认 0