logging:
  path: /mnt/logs #日志输出位置
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n" #控制台日志数据格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n" #输出格式
    dateformat: yyyy-MM-dd HH:mm:ss #日志时间格式
    level: INFO  #日志输出级别
  file:
    max-size: 500MB
    max-history: 1